name: ci
on:
  pull_request:
  push:

env:
  THREADS_WORKER_INIT_TIMEOUT: 15000

jobs:
  # Building threads library from source
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: "latest"
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies and build
        run: yarn install

      - name: Dev test
        run: yarn test

      - name: Upload artifacts
        if: contains(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./bundle
            ./dist
            ./test-tooling/webpack/dist

  # Testing the built files
  Test:
    needs: Build
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: "latest"
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        run: yarn install --ignore-scripts

      - name: Download articats
        uses: actions/download-artifact@v2

      - name: Place built files
        shell: bash
        run: |
          mkdir dist && mv artifact/dist/* ./dist
          mkdir bundle && mv artifact/bundle/* ./bundle

      - name: run the tests
        run: yarn test

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
