name: Release npm package

on:
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: npx semantic-release --branches master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
